export const firstStrike = 'api/singletons/get/first_strike'
export const secondStrike = 'api/singletons/get/second_strike'
export const thirdStrike = 'api/singletons/get/Third_Strike'
export const fourthStrike = 'api/singletons/get/Fourth_Strike'
export const fifthStrike = 'api/singletons/get/Fifth_Strike'
export const sixStrike = 'api/singletons/get/Sixth_Strike'
export const sevenStrike = 'api/singletons/get/Seven_Strike'
export const eightStrike = 'api/singletons/get/Eighth_Strike'
export const nineStrike = 'api/singletons/get/Nine_Strike'
export const tenStrike = 'api/singletons/get/Page_10'
export const elevenStrike = 'api/singletons/get/Eleven_Strike'

export const twelfthStrike = 'api/singletons/get/Twelve_Strike'
export const thirteenStrike = 'api/singletons/get/Thirteen_Strike'
export const fourteenStrike = 'api/singletons/get/Fourteen_Strike'
export const fifthteen= 'api/singletons/get/Fifthteen_Strike'
export const sixteenStrike = 'api/singletons/get/Sixteen_Strike'
// Tobe Done 
	
export const DashboardData = '/.netlify/functions/users-read-all'